### ISSUE TITLE
What's the rationale behind having it only work for workstations?

### ISSUE THREAD

**Issue by kelvie** [openshift/coredns-mdns#84]
Hello,

I'm using coredns as my main home internet DNS, and since switching to ipv6, found that mdns is almost a necessity without the dhcp -> dns that most dhcp servers provide.

Anyway, most linux machines don't enable "publish-workstations" (e.g. my Synology box) -- is there a rationale for why this is hard coded, and why we can't turn this off (it is also strange as a sensible default).

**Comment by cybertron** [comment]
Honestly, the only reason is that this was implemented with the specific use case of OpenShift in mind. We've made a few changes over the years to support other use cases, but at this point we're no longer using this in OpenShift so from our side it's largely abandoned.

**Comment by kelvie** [comment]
Okay, will you take submissions / PRs still? Or should I fork this?

**Comment by cybertron** [comment]
You've probably figured this out by now, but forking is a good idea. This is way down our priority list now that we're not using it so we most likely won't be providing timely feedback (case in point: this response :-).
